using System.Collections.Immutable;
using System.Linq;
using System.Text;
using BitSerializer.Generator.Analysis;
using BitSerializer.Generator.Emitters;
using BitSerializer.Generator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BitSerializer.Generator;

[Generator]
public class BitSerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var allResults = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "BitSerializer.BitSerializeAttribute",
                predicate: (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: (ctx, ct) => TypeAnalyzer.Analyze(ctx, ct));

        // Report diagnostics for non-partial types
        context.RegisterSourceOutput(allResults, (spc, result) =>
        {
            if (result is null) return;
            if (result.Diagnostic is not null)
            {
                spc.ReportDiagnostic(result.Diagnostic);
                return;
            }
            if (result.Model is null) return;
            var source = GeneratePartialClass(result.Model);
            var fileName = result.Model.FullyQualifiedName
                .Replace("global::", "")
                .Replace(".", "_")
                .Replace("+", "_")
                .Replace("<", "_")
                .Replace(">", "")
                .Replace(",", "_")
                .Replace(" ", "");
            spc.AddSource($"{fileName}.g.cs", source);
        });

        // Generate registry
        var validModels = allResults
            .Where(r => r?.Model is not null)
            .Select((r, _) => r!.Model);
        var allTypes = validModels.Collect();
        context.RegisterSourceOutput(allTypes, RegistryEmitter.Emit);
    }

    private static string GeneratePartialClass(TypeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        // sb.AppendLine($"// HasBase={model.HasBitSerializableBaseType} BaseBitLength={model.BaseBitLength} TotalBitLength={model.TotalBitLength} Fields={model.Fields.Count}");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // Open containing types (for nested types)
        int nestingDepth = model.ContainingTypes.Count;
        foreach (var container in model.ContainingTypes)
        {
            var containerKeyword = GetTypeKeyword(container.IsClass, container.IsRecord);
            sb.AppendLine($"partial {containerKeyword} {container.Name}");
            sb.AppendLine("{");
        }

        var typeKeyword = GetTypeKeyword(model.IsClass, model.IsRecord);
        var indent = new string(' ', nestingDepth * 4);
        sb.AppendLine($"{indent}partial {typeKeyword} {model.TypeName} : global::BitSerializer.IBitSerializable");
        sb.AppendLine($"{indent}{{");

        // SerializeLSB (context-aware, primary implementation)
        sb.Append(SerializerEmitter.EmitMethod(model, "LSB"));
        sb.AppendLine();

        // SerializeMSB (context-aware, primary implementation)
        sb.Append(SerializerEmitter.EmitMethod(model, "MSB"));
        sb.AppendLine();

        // DeserializeLSB (context-aware, primary implementation)
        sb.Append(DeserializerEmitter.EmitMethod(model, "LSB"));
        sb.AppendLine();

        // DeserializeMSB (context-aware, primary implementation)
        sb.Append(DeserializerEmitter.EmitMethod(model, "MSB"));
        sb.AppendLine();

        // Non-context delegation methods
        sb.Append(SerializerEmitter.EmitDelegationMethod(model, "LSB"));
        sb.Append(SerializerEmitter.EmitDelegationMethod(model, "MSB"));
        sb.Append(DeserializerEmitter.EmitDelegationMethod(model, "LSB"));
        sb.Append(DeserializerEmitter.EmitDelegationMethod(model, "MSB"));
        sb.AppendLine();

        // Partial methods for user context access
        sb.AppendLine("    partial void OnSerializing(object? context);");
        sb.AppendLine("    partial void OnDeserializing(object? context);");
        sb.AppendLine();

        // GetTotalBitLength
        var newKeyword = model.HasBitSerializableBaseType ? "new " : "";
        if (model.HasDynamicLength)
        {
            sb.AppendLine($"    public {newKeyword}int GetTotalBitLength()");
            sb.AppendLine("    {");
            EmitDynamicBitLength(sb, model);
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public {newKeyword}int GetTotalBitLength() => {model.TotalBitLength};");
        }

        sb.AppendLine($"{indent}}}");

        // Close containing types
        for (int i = nestingDepth - 1; i >= 0; i--)
        {
            var closeIndent = new string(' ', i * 4);
            sb.AppendLine($"{closeIndent}}}");
        }

        return sb.ToString();
    }

    private static string GetTypeKeyword(bool isClass, bool isRecord)
    {
        if (isRecord)
            return isClass ? "record class" : "record struct";
        return isClass ? "class" : "struct";
    }

    /// <summary>
    /// Returns a null-safe expression for the actual collection length (e.g. "this.Items?.Count ?? 0").
    /// Used in GetTotalBitLength which must remain side-effect free and null-safe.
    /// </summary>
    private static string ListLengthExpr(BitFieldModel field)
    {
        var lengthProp = field.IsArray ? "Length" : "Count";
        return $"(this.{field.MemberName}?.{lengthProp} ?? 0)";
    }

    private static void EmitDynamicBitLength(StringBuilder sb, TypeModel model)
    {
        // Start with static portion (include base type bits)
        int staticBits = model.BaseHasDynamicLength ? 0 : model.BaseBitLength;
        var dynamicParts = new System.Collections.Generic.List<string>();
        var preStatements = new System.Collections.Generic.List<string>();

        if (model.BaseHasDynamicLength)
        {
            dynamicParts.Add("base.GetTotalBitLength()");
        }

        foreach (var field in model.Fields)
        {
            if (field.IsTypeParameter)
            {
                // Type parameter: bit length unknown at compile time, use interface dispatch
                dynamicParts.Add($"((global::BitSerializer.IBitSerializable)this.{field.MemberName}).GetTotalBitLength()");
            }
            else if (field.IsList && field.ListElementIsManualBitSerializable)
            {
                if (field.FixedCount.HasValue && field.ListElementBitLength > 0)
                {
                    // Fixed-count with explicit element width: treat as static
                    staticBits += field.FixedCount.Value * field.ListElementBitLength;
                }
                else
                {
                    // Manual IBitSerializable list elements: sum actual element bit lengths
                    var sumVar = $"_sumBits_{field.MemberName}";
                    string countExpr = field.FixedCount.HasValue
                        ? field.FixedCount.Value.ToString()
                        : ListLengthExpr(field);
                    preStatements.Add($"        int {sumVar} = 0;");
                    preStatements.Add($"        for (int _i = 0; _i < {countExpr}; _i++)");
                    preStatements.Add($"            {sumVar} += ((global::BitSerializer.IBitSerializable)this.{field.MemberName}[_i]).GetTotalBitLength();");
                    dynamicParts.Add(sumVar);
                }
            }
            else if (field.IsList && field.ListElementHasDynamicLength)
            {
                // [BitSerialize] list elements with dynamic length: sum actual element bit lengths
                var sumVar = $"_sumBits_{field.MemberName}";
                string countExpr = field.FixedCount.HasValue
                    ? field.FixedCount.Value.ToString()
                    : ListLengthExpr(field);
                preStatements.Add($"        int {sumVar} = 0;");
                preStatements.Add($"        for (int _i = 0; _i < {countExpr}; _i++)");
                preStatements.Add($"            {sumVar} += ((global::BitSerializer.IBitSerializable)this.{field.MemberName}[_i]).GetTotalBitLength();");
                dynamicParts.Add(sumVar);
            }
            else if (field.IsList && !field.FixedCount.HasValue)
            {
                // Dynamic list: use actual collection length directly (side-effect free)
                dynamicParts.Add($"{ListLengthExpr(field)} * {field.ListElementBitLength}");
            }
            else if (field.IsList && field.FixedCount.HasValue)
            {
                staticBits += field.FixedCount.Value * field.ListElementBitLength;
            }
            else if (field.IsTerminatedString)
            {
                var encoding = GetEncodingExpression(field.StringEncodingName);
                var tsVar = $"_ts_{field.MemberName}";
                preStatements.Add($"        string {tsVar} = this.{field.MemberName} ?? \"\";");
                preStatements.Add($"        int _tsNul_{field.MemberName} = {tsVar}.IndexOf('\\0');");
                preStatements.Add($"        if (_tsNul_{field.MemberName} >= 0) {tsVar} = {tsVar}.Substring(0, _tsNul_{field.MemberName});");
                dynamicParts.Add($"({encoding}.GetByteCount({tsVar}) + 1) * 8");
            }
            else if (field.IsPotentiallyDynamic)
            {
                dynamicParts.Add($"((global::BitSerializer.IBitSerializable)this.{field.MemberName}).GetTotalBitLength()");
            }
            else
            {
                staticBits += field.BitLength;
            }
        }

        foreach (var stmt in preStatements)
        {
            sb.AppendLine(stmt);
        }

        var expr = staticBits.ToString();
        foreach (var part in dynamicParts)
        {
            expr += $" + {part}";
        }
        sb.AppendLine($"        return {expr};");
    }

    private static string GetEncodingExpression(string encodingName)
    {
        return encodingName == "UTF8"
            ? "global::System.Text.Encoding.UTF8"
            : "global::System.Text.Encoding.ASCII";
    }
}
