using System.Collections.Immutable;
using System.Linq;
using System.Text;
using BitSerializer.Generator.Models;
using Microsoft.CodeAnalysis;

namespace BitSerializer.Generator.Emitters;

internal static class RegistryEmitter
{
    public static void Emit(SourceProductionContext context, ImmutableArray<TypeModel?> models)
    {
        var validModels = models.Where(m => m != null).ToList();
        if (validModels.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace BitSerializer;");
        sb.AppendLine();
        sb.AppendLine("internal static class BitSerializerRegistryInit");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        foreach (var model in validModels)
        {
            sb.AppendLine($"        global::BitSerializer.BitSerializerRegistry.Register<{model!.FullyQualifiedName}>();");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("BitSerializerRegistryInit.g.cs", sb.ToString());
    }
}
